# Generated by Django 5.2.3 on 2025-08-28 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=90)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('movie_poster_url', models.URLField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='movieRecommendationService.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'added_at'], name='movieRecomm_user_id_8ed650_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movies_saved')],
            },
        ),
    ]
