# Generated by Django 5.2.3 on 2025-09-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommendationService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
