# Generated by Django 5.2.3 on 2025-09-04 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommendationService', '0003_watchedmovies'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=90)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('movie_poster_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='watchedmovies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='movieRecommendationService.watchedmovie'),
        ),
    ]
