import type { Metadata } from "next";
import StoreProvider from "./redux/StoreProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ST } from "next/dist/shared/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        { /* Provide the redux store to the application */}
        <StoreProvider>
        {children}
        </StoreProvider>
      </body>
    </html>
  );
}
